version: "3.9"

services:
  web:
    image: phpstorm/php-apache:8.0-xdebug3.0
    container_name: servidor-web3
    ports:
      - 80:80
      - 443:433
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - Apache:/var/www/html
    networks:
      - default

  db:
    image: 'mysql'
    container_name: servidor-mysql3
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: banco
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: quevedo
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer3
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
      - web
    networks:
      - default

networks:
  default:

volumes:
  webapp:
  db-data: